PerfectCRM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from PerfectCRM import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r"^$",views.index ),
    url(r'^admin/', admin.site.urls),
    url(r'^crm/',include("crm.urls")),
    url(r'^accounts/login/$',views.acc_login),
    url(r'^accounts/logout/$',views.acc_logout,name="acc_logout"),
    url(r'^student/',include("student.urls")),
    url(r'^king_admin/', include("king_admin.urls")),

]

crm/urls.py
# rex.zhu


from django.conf.urls import url
from crm import  views
urlpatterns = [
    url(r"^$",views.index,name="sales_index"),
    url(r"^customers/$",views.customer_list,name="customers_list"),
    url(r'customers/(\d+)/enrollment/$', views.enrollment, name="enrollment"),
    url(r'customers/stu_registration/(\d+)/(\w+)/$', views.student_registration, name="student_registration"),
    url(r'contract_review/(\d+)/$', views.contract_review, name="contract_review"),
    url(r'payment/(\d+)/$', views.payment, name="payment"),
    url(r'enrollment_rejection/(\d+)/$',views.enrollment_rejection,name="enrollment_rejection")
]

student/urls.py
# rex.zhu


from django.conf.urls import url
from student import views
urlpatterns = [
    url(r"^$",views.stu_my_classes,name="stu_my_classes"),
    url(r"^studyrecords/(\d+)/$",views.studyrecords,name="studyrecords"),
    url(r"^homework_detail/(\d+)/$",views.homework_detail,name="homework_detail"),
]

crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,PermissionsMixin
)
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _



# # Create your models here.
#
class Customer(models.Model):
    #"客户信息表"
    name =models.CharField(max_length=32,null=True,blank=True,help_text="请输入真实姓名")
    qq = models.CharField(max_length=64,unique=True,)
    qq_name = models.CharField(max_length=64,blank=True,null=True)
    phone = models.CharField(max_length=64,blank=True,null=True)
    id_num = models.CharField(max_length=64,blank=True,null=True)
    email = models.EmailField(verbose_name="常用邮箱",blank=True,null=True)
    source_choices = ( (0,'转介绍'),
                       (1,'QQ群'),
                       (2,'官网'),
                       (3,'百度推广'),
                       (4,'51CTO'),
                       (5,'知乎'),
                       (6,'市场推广')
                      )
    source = models.SmallIntegerField(choices=source_choices)
    referral_from = models.CharField(verbose_name="转介绍人QQ",max_length=64,blank=True,null=True)
    consult_course = models.ForeignKey("Course",verbose_name="咨询课程",on_delete=models.CASCADE)
    content = models.TextField(verbose_name="咨询详情")
    tags = models.ManyToManyField("Tag",blank=True,null=True)
    consultant = models.ForeignKey("UserProfile",on_delete=models.CASCADE)   #顾问

    status_choices = ((0, '已报名'),
                      (1, '未报名'),
                      )
    status = models.SmallIntegerField(choices=status_choices, default=1)
    memo = models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "客户表"            #在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "客户表"     #加上这和把s 去掉




class Tag(models.Model):
    name = models.CharField(max_length=32,unique=True)

    class Meta:
        verbose_name = "标签"  # 只加这个会显示客户表s ,
        verbose_name_plural = "标签"

    def __str__(self):
        return self.name


class CustomerFollowUp(models.Model):
    #"客户跟 进表"
    customer = models.ForeignKey("Customer",on_delete=models.CASCADE)
    content = models.TextField(verbose_name="跟进内容")
    consultant =  models.ForeignKey("UserProfile",on_delete=models.CASCADE)
    date =  models.DateTimeField(auto_now_add=True)
    intention_chices = (
        (0,"2周内报名"),
        (1,"1周内报名"),
        (2,"近期无报名计划"),
        (3,"已在其它机构报名"),
        (4,"已拉黑"),
        (5,"已报名"),
    )
    intention = models.SmallIntegerField(choices=intention_chices)
    date =  models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "<%s,%s>"%(self.customer.qq,self.intention)

    class Meta:
        verbose_name = "客户跟进记录"            #在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "客户跟进记录"     #加上这和把s 去掉


class Course(models.Model):
    #"课程表"
    name =  models.CharField(max_length=64,unique=True)
    price =  models.PositiveSmallIntegerField()
    period = models.PositiveIntegerField(verbose_name="周期（月）")
    outline   =models.TextField()  #大纲

    class Meta:
        verbose_name = "课程表"            #在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "课程表"     #加上这和把s 去掉
    def __str__(self):
        return self.name


class Branch(models.Model):
    #"校区"
    name = models.CharField(max_length=128,unique=True)
    addr = models.CharField(max_length=128)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "校区"            #在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "校区"     #加上这和把s 去掉

class ClassList(models.Model):
    "班级表"
    course =  models.ForeignKey("Course",on_delete=models.CASCADE)
    class_type_choices = ((0,"面授(脱产)"),
                          (1,"面授(周末)"),
                          (2,"网络班"),
    )
    contract =  models.ForeignKey("ContractTemplate",blank=True,null=True,on_delete=models.CASCADE)
    class_type =  models.SmallIntegerField(choices=class_type_choices,verbose_name="班级类型")
    semester = models.PositiveSmallIntegerField(verbose_name="学期")
    teachers = models.ManyToManyField("UserProfile")
    branch  = models.ForeignKey("Branch",on_delete=models.CASCADE)
    start_date = models.DateField(verbose_name="开班日期")
    end_date =  models.DateField(verbose_name="结业日期",blank=True,null=True)

    def  __str__(self):
        return "%s %s %s"%(self.branch,self.course,self.semester)

    class Meta:
        unique_together = ("branch","course","semester")
        verbose_name = "班级表"  # 在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "班级表"  # 加上这和把s 去掉


class CourseRecord(models.Model):
    "课程记录"
    from_class = models.ForeignKey("ClassList",verbose_name="班级",on_delete=models.CASCADE)
    day_num =  models.PositiveSmallIntegerField(verbose_name="第几天(节)")
    teacher = models.ForeignKey("UserProfile",on_delete=models.CASCADE)
    has_homework =  models.BooleanField(default=True)
    homework_title =  models.CharField(max_length=128,blank=True,null=True)
    outline =  models.TextField(verbose_name="本节课程大纲")
    date =  models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s %s" %(self.from_class,self.day_num)

    class Meta:
        unique_together = ("from_class","day_num")
        verbose_name = "上课记录"  # 在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "上课记录"  # 加上这和把s 去掉



    pass

class StudyRecord(models.Model):
    "学习记录"
    student = models.ForeignKey("Enrollment",on_delete=models.CASCADE)
    course_record =  models.ForeignKey("CourseRecord",on_delete=models.CASCADE)
    attendance_choices = (
        (0,"已签到"),
        (1,"迟到"),
        (2,"缺席"),
        (3,"早退"),
   )
    attendance = models.SmallIntegerField(choices=attendance_choices,default=0)

    score_choices = (
        (100,"A+"),
        (90,"A"),
        (85,"B+"),
        (80,"B"),
        (75,"B-"),
        (70,"C+"),
        (60,"C"),
        (40,"C-"),
        (-50,"D"),
        (-100,"COPY"),
        (0,"N/A"),
    )
    score = models.SmallIntegerField(choices=score_choices,default=0)
    memo = models.TextField(blank=True,null=True)
    date  = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s %s %s"%(self.student,self.course_record,self.score)

    class Meta:
        unique_together = ("student","course_record")
        verbose_name = "学习记录"  # 在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "学习记录"  # 加上这和把s 去掉



class Enrollment(models.Model):
    "报表名"
    customer = models.ForeignKey("Customer",on_delete=models.CASCADE)
    enrollment_class =  models.ForeignKey("ClassList",verbose_name="所报班级",on_delete=models.CASCADE)
    consultant =  models.ForeignKey("UserProfile",verbose_name="课程顾问",on_delete=models.CASCADE)
    contract_agreed = models.BooleanField(default=False,verbose_name="学员已同意合同")
    contract_approved =  models.BooleanField(default=False,verbose_name="合同已审核")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s"%(self.customer,self.enrollment_class)

    class Meta:
        unique_together = ("customer","enrollment_class")
        verbose_name = "报名表"  # 在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "报名表"  # 加上这和把s 去掉




class Payment(models.Model):

    customer = models.ForeignKey("Enrollment",on_delete=models.CASCADE)
    course =  models.ForeignKey("Course",verbose_name="所报课程",on_delete=models.CASCADE)
    amount =  models.PositiveSmallIntegerField(verbose_name="数额",default=500)
    consultant =  models.ForeignKey("UserProfile",on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "缴费表"  # 在django中表名显示中文，只加这个会显示客户表s ,
        verbose_name_plural = "缴费表"  # 加上这和把s 去掉

    def __str__(self):
        return "<%s %s>"%(self.customer,self.amount)

#
# class UserProfile(models.Model):
#     #"帐号表"
#     #from django.contrib.auth.models import User
#     user = models.OneToOneField(User,on_delete=models.CASCADE)
#     name = models.CharField(max_length=32)
#     roles = models.ManyToManyField("Role",blank=True,null=True)
#
#     def __str__(self):
#         return self.name

class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        self.is_active = True
        user.save(using=self._db)
        return user

    def create_superuser(self,email, name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_active = True
        user.is_admin = True
        user.save(using=self._db)
        return user


class UserProfile(AbstractBaseUser,PermissionsMixin):
    '''账号表'''
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
        null=True
    )

    password = models.CharField(_('password'), max_length=128,help_text=mark_safe("<a href='password/'>修改密码</a>"))

    name = models.CharField(max_length=32)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    roles  =  models.ManyToManyField("Role",blank=True)

    objects = UserProfileManager()

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render

# Create your views here.
from crm import models
from PerfectCRM import settings
from django.shortcuts import redirect,HttpResponse
import json,os,time

def stu_my_classes(requet):
    return render(requet,"student/my_classes.html",{})


def  studyrecords(request,enrollment_id):
    enroll_obj = models.Enrollment.objects.get(id=enrollment_id)
    print(enroll_obj)
    return  render(request,"student/studyrecords.html",{"enroll_obj":enroll_obj})


def homework_detail(request,studyrecord_id):
    # studyrecord_obj = models.StudyRecord.objects.get(id=studyrecord_id)
    # return render(request, "student/homework_detail.html",{"studyrecord_obj":studyrecord_obj})

    studyrecord_obj = models.StudyRecord.objects.get(id=studyrecord_id)
    homework_path = "{base_dir}/{class_id}/{course_record_id}/{studyrecord_id}/" \
        .format(base_dir=settings.HOMEWORK_DATA,
                class_id=studyrecord_obj.student.enrollment_class_id,
                course_record_id=studyrecord_obj.course_record_id,
                studyrecord_id=studyrecord_obj.id
                )
    if not os.path.isdir(homework_path):
        os.makedirs(homework_path, exist_ok=True)



    if request.method == "POST":
        print(request.FILES)
        #class_id/course_record_id/studyrecord_id
        for k,file_obj in request.FILES.items():
            with open("%s/%s"%(homework_path,file_obj.name),"wb" ) as f :
                for chunk in file_obj.chunks():
                    f.write(chunk)

        #return HttpResponse(json.dumps({"status":0, "msg":"file upload success"}))
    if request.GET.get("delete"):
        file_name=request.GET.get("delete")
        f_path = "%s/%s" % (homework_path, file_name)
        os.remove(f_path)


    file_lists = []
    for file_name in os.listdir(homework_path):
        f_path = "%s/%s" % (homework_path,file_name)
        modify_time =time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(os.stat(f_path).st_mtime) )
        file_lists.append([file_name,  os.stat(f_path).st_size,modify_time])
    print("file lists",file_lists)


    if request.method == "POST":
        return HttpResponse(json.dumps({"status": 0,
                                        "msg": "file upload success",
                                        'file_lists':file_lists}))
    return render(request,"student/homework_detail.html",
                  {"studyrecord_obj":studyrecord_obj,
                   "file_lists":file_lists})

templates/student/homework_detail.html
{%  extends 'index.html' %}
{% load tags %}
{% block page-content %}

  <!-- Default panel contents -->
  <div class="panel-heading">班级:{{ studyrecord_obj.student.enrolled_class }}  | 节次{{ studyrecord_obj.course_record.day_num }}</div>
  <div class="panel-body">
        <h4>作业标题:{{ studyrecord_obj.course_record.homework_title }}</h4>
        <h4>作业详情：<pre>{{ studyrecord_obj.course_record.homework_content }}</pre></h4>
        <h4>老师评语:{{ studyrecord_obj.memo }}</h4>
        <h4>本节成绩:{{ studyrecord_obj.score }}</h4>


        <div class="row">
            <p>已上传作业</p>
            <ul>
                {% for file in file_lists %}
                    <li>{{ file.0 }} | {{ file.1 }} | {{ file.2 }} <a href="?delete={{ file.0 }}">删除</a></li>
                {% endfor %}
            </ul>
        </div>

        <p>请上传你的作业</p>
        <form  method="post" action="{{ request.path }}" style="border:1px dashed lightblue;height: 250px" class="dropzone form-horizontal"  role="form" id="my-awesome-dropzone">
                      <div class="fallback form-group">
                          <div class="col-sm-9  col-md-offset-2">
                                <input name="file" type="file"   multiple />
                          </div>
                      </div>
        </form>

  <!-- Table -->
</div>
{% endblock %}

templates/student/index.html
{% extends "index.html" %}

{%  block page-content %}

    学生首页

{% endblock %}

templates/student/my_classes.html
{% extends "index.html" %}
{% load tags %}


{%  block page-content %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">我的课程</h3>
  </div>
  <div class="panel-body">

      {{ request.user.stu_account }}

              <table class="table table-hover">
                  <thead>
                    <tr>
                        <th>课程名称</th>
                        <th>班级</th>
                        <th>开课日期</th>
                        <th>结业日期</th>
                        <th>课程进度</th>
                        <th>我的成绩</th>
                        <th>学习记录</th>
                    </tr>
                  </thead>
                  <tbody>
                  {%  for enroll_obj in request.user.stu_account.enrollment_set.all %}
                    <tr>
                        <td>{{ enroll_obj.enrollment_class.course }}</td>
                        <td>{{ enroll_obj.enrollment_class }}</td>
                        <td>{{ enroll_obj.enrollment_class.start_date }}</td>
                        <td>{{ enroll_obj.enrollment_class.end_date }}</td>
                        <td>{{ enroll_obj.enrollment_class.courserecord_set.all.count }}</td>
                        <td>{% get_score  request enroll_obj %}</td>
                        <td><a href="{% url 'studyrecords' enroll_obj.id %}">学习记录</a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr><td></td><td><p> total :  条记录</p></td></tr>
                  </tfoot>
              </table>


  </div>
</div>

{% endblock %}

templates/student/studyrecords.html
{% extends "index.html" %}
{% load tags %}


{%  block page-content %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">学习记录</h3>
  </div>
  <div class="panel-body">

      {{ request.user.stu_account }}

              <table class="table table-hover">
                  <thead>
                    <tr>
                        <th>课程节次</th>
                        <th>上课日期</th>
                        <th>是否有作业</th>
                        <th>作业标题</th>
                        <th>签到状态</th>
                        <th>成绩</th>
                        <th>作业管理</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for studyrecod in enroll_obj.studyrecord_set.all %}
                        <tr>
                        <td>{{studyrecod.course_record.day_num}}</td>
                        <td>{{studyrecod.course_record.date}}</td>
                        <td>{{studyrecod.course_record.has_homework}}</td>
                        <td>{{studyrecod.course_record.homework_title}}</td>
                        <td>{{ studyrecod.get_attendance_display }}</td>
                        <td>{{ studyrecod.get_score_display }}</td>
                        <td><a href="{% url "homework_detail" studyrecod.id %}">作业管理</a> </td>
                        </tr>
                    {% endfor %}


                  </tbody>
                  <tfoot>
                  <tr><td></td><td><p> total :  条记录</p></td></tr>
                  </tfoot>
              </table>


  </div>
</div>

{% endblock %}